Trying connect to google account to get last build number

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -9,7 +9,7 @@ workflows:
 #            - keystore_reference
           groups:
              - devel
-#            - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS <-- Put your google-services.json)
+             - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS <-- Put your google-services.json)
           vars:
             PACKAGE_NAME: "io.kogito.sample.reactnative" # <-- Put your package name here e.g. com.domain.myapp
           node: v16.11.1
@@ -24,21 +24,22 @@ workflows:
               script: |
                 echo $KEYSTORE_CONTENT | base64 --decode > android/app/key.jks
             - name: Build Android release
-#              script: |
-#                LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
-#                if [ -z LATEST_BUILD_NUMBER ]; then
-#                  # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
-#                  UPDATED_BUILD_NUMBER=$BUILD_NUMBER
-#                else
-#                  UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
-#                fi
               script: |
-                cd android
-                ./gradlew bundleRelease
+                LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
+                if [ -z LATEST_BUILD_NUMBER ]; then
+                  # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
+                  UPDATED_BUILD_NUMBER=$BUILD_NUMBER
+                else
+                  UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
+                fi
+                println "Number is $UPDATED_BUILD_NUMBER"
+#              script: |
+#                cd android
+#                ./gradlew bundleRelease
 #                  -PversionCode=$UPDATED_BUILD_NUMBER \
 #                  -PversionName=1.0.$UPDATED_BUILD_NUMBER
-        artifacts:
-             - android/app/build/outputs/**/*.aab
+#        artifacts:
+#             - android/app/build/outputs/**/*.aab
 #        publishing:
 #          email:
 #            recipients:
